### ISSUE TITLE
discovery and not discover

### ISSUE THREAD

**Issue by gperreymond** [aholstenson/ataraxia#1]
On documentation you indicate : discover: true/false
But it is discovery

BTW excellent work dude.
Gilles

**Comment by HossamSamir** [comment]
Also any workaround to auto discover instances that not in the LAN?

**Comment by 0x77dev** [comment]
@HossamSamir you will need to write custom transport and discovery for your needs.

**Comment by aholstenson** [comment]
Docs have been updated and overhauled
