### ISSUE TITLE
Support for merging multiple local and remote services

### ISSUE THREAD

**Issue by aholstenson** [aholstenson/ataraxia#10]
The services library should support merging services with the same identifier, no matter if they are local or remote. This merging should support different policies for method invocation, such as random invocation, round robin invocation and invoke all.

**Comment by aholstenson** [comment]
Support for this is available since 0.11.0

**Comment by iamyellow** [comment]
hey! I'm trying to figure it out how this work... In my use case I need every node implement the same service method. The thing is almost always the local method impl is triggered, which makes sense... but I'd like to have some -remote only- policy. Is there any way? I could help.
