### ISSUE TITLE
STUN server implementation 

### ISSUE THREAD

**Issue by 0x77dev** [aholstenson/ataraxia#18]
Implement a Websocket STUN server for ataraxia.

I don't have so many soft skills, so I will describe by diagram:

<img width="656" alt="Снимок экрана 2020-07-13 в 23 37 23" src="https://user-images.githubusercontent.com/46429701/87351231-cffa2c00-c561-11ea-8c16-86a3f863419b.png">

**Comment by 0x77dev** [comment]
Maybe create some Atatraxia node as a STUN server and implement a routing system for multiple networks

**Comment by aholstenson** [comment]
If you are still looking for a way to connect two networks together the new package `ataraxia-hyperswarm` might be what you're looking for.

```javascript
import { HyperswarmTransport } from 'ataraxia-hyperswarm';

new HyperswarmTransport({
  topic: 'topic used to find peers over the internet',
  authentication: [
     ...
  ]
});
```
