### ISSUE TITLE
Lots of nodes that doesn't exists anymore and not easy to identify each node.

### ISSUE THREAD

**Issue by YindSoft** [aholstenson/ataraxia#19]
Hi!, I'm using the module to connect 10 computers with each other sending messages and it works fine.
But I have 2 issues.
1), After using it a while and restartarting some of the nodes, I find that there are lots of nodes "connected" to the network when there should be only 10 at all time.. I'm using the shared secret key method.
`Node Node{yStDO0zAWp} is now available
Node Node{yR9xwi5paz} is now available
Node Node{yR18K08mxT} is now available
Node Node{yRWrUcvrxD} is now available
Node Node{yRWIJo8IAH} is now available
Node Node{yR1aukhYkP} is now available
Node Node{yRWBdguqmM} is now available
Node Node{yR13e7jJWu} is now available
Node Node{9GgOAP04RC} is now available
Node Node{9GgOAA5Sts} is now available
Node Node{yR1NHdQDYh} is now available
Node Node{yR10mArnua} is now available
Node Node{yR1NHdQDYh} is no longer available
Node Node{yR1NHtD9iD} is now available
Node Node{yR10mArnua} is no longer available
Node Node{yR1NHdQDYh} is now available
Node Node{yRVWEqgwG5} is now available
Node Node{yR1bNvp9i4} is now available
Node Node{yR10mArnua} is now available
Node Node{yR04KUSt0a} is now available
Node Node{yR0Lx6M0iT} is now available
Node Node{9GgOBIvtJ6} is now available
Node Node{9GgOPiUeVM} is now available
Node Node{9GgOBGiwOY} is now available
Node Node{9GgOxwBIZz} is now available
Node Node{yR11FqmySh} is now available
Node Node{yR18q2HVNz} is now available
Node Node{yR18Sw5Pw8} is now available
Node Node{yR2higsdFb} is now available
Node Node{yR6UCbzvV1} is now available
Node Node{yR7biFXYon} is now available
Node Node{yR7SXX5UW0} is now available
Node Node{yR887s0frj} is now available
Node Node{yR8kis7pSU} is now available
Node Node{yR8xeS4dij} is now available
Node Node{yR8KmbMesR} is now available
Node Node{yR8MZXR6oU} is now available
Node Node{yR9bRFovWT} is now available
Node Node{yR9u35ZFEG} is now available
Node Node{yRWwqMgQGF} is now available
`
This is what I'm seeing right now when I restart one of the modules.

Also sometimes, some of the nodes won't connect with an especific one, but I can send messages from the other to that one. For example. I can send a message from A to B, but not from B to A.

And the last thing is that the random id "yR9u35ZFEG" is okay, but there should be a way to initialize a node with a custom alias for example:
`const net = new Network({
    name: config.networkName,
    alias: 'pc-4',
    authentication: [
        new SharedSecretAuth({ secret: config.secretAuth })
    ]
});`

So when I'm debugging I can see which node is which.

Also should give you your own ID.

In net.onNodeAvailable I will receive my own node when someone else is connected to the network and I will throw an error If I send something to that node, It should ignore the event if the node is itself.

Besides that, the module is well organized and easy to use.
Thank you.

**Comment by aholstenson** [comment]
Thanks for the report! Sorry for being so slow to respond. I've recently found some time to spend on this project, and the issue with nodes not being marked as unavailable should be resolved in the latest release.

For named ids that's something outside the scope for now, id must be unique and are always an auto-generated value set when the network is started
