### ISSUE TITLE
Node Unavailable Event not raised?

### ISSUE THREAD

**Issue by Catutigernos** [aholstenson/ataraxia#20]
Hi, I tried your example. When a node connect, no problem available node event raised, but when I destroyed one of node. Unavailable event not raised, until a new node connect. And I want to ask how many node can connect? and Is project active? I saw some issue post which is not answered.

Thanks in advance.

`/**
 * This example starts a network named `example` and uses a TCP transport with
 * discovery of peers on the same network using mDNS.
 *
 * It will log when new nodes are discovered and when messages are received.
 * In addition to this it sends a hello to nodes when they are seen and
 * broadcasts a counter every 5 seconds to all current nodes.
 */

//  const { Network, AnonymousAuth } = require('../packages/core');
//  const { TCPTransport, TCPPeerMDNSDiscovery } = require('../packages/tcp');
 const { Network, AnonymousAuth, Exchange } = require('ataraxia');
 const { TCPTransport, TCPPeerMDNSDiscovery } = require('ataraxia-tcp');
 
 const net = new Network({
     name: 'example',
     authentication: [
         new AnonymousAuth()
     ]
 });

async function counter(net) {

	let counter = 0;

	const exchange = new Exchange(net, 'counter');
	exchange.onNodeAvailable(node => {
		node.send('hello', { counter: counter });
	})

	await exchange.join();

	// Increment and broadcast counter to all nodes every five seconds
	setInterval(() => {
		exchange.broadcast('counter', { current: ++counter });
	}, 5000);

}
 // Add the TCP transport with mDNS discovery
 net.addTransport(new TCPTransport({
     discovery: new TCPPeerMDNSDiscovery()
 }));
 
 // Log when new nodes are available and send them a hello with the counter
 net.onNodeAvailable(node => {
     console.log('Node', node, 'is now available');
 });
 
 net.onNodeUnavailable(node => {
     console.log('Node', node, 'is no longer available');
 });
 
 // Log when messages have been received
 net.onMessage(msg => {
     console.log('Message was received:', 'type=', msg.type, 'data=', msg.data, 'source=', msg.source);
 });
 
 // Start the network
 net.start()
     .then(() => {
         console.log('Network has started with id', net.networkId);
 
         // Start our helper
         //return require('./helpers/counter')(net);
         //return counter(net);
     })
     .catch(err => console.error(err));`

**Comment by aholstenson** [comment]
Thanks for the report! Sorry for being so slow to respond. I've recently found some time to spend on this project, and this issue should be resolved in the latest release.
