### ISSUE TITLE
What about Tor transport?

### ISSUE THREAD

**Issue by 0x77dev** [aholstenson/ataraxia#3]
> Maybe ataraxia can use Tor to communicate with other peers?
make some sort of `ataraxia-transport-tor` library.

**Comment by aholstenson** [comment]
That's an interesting idea, I spent a bit of time looking at Tor support for Node and there are a few solutions that use an external Tor client. But for now it's not something I will be focusing on.

**Comment by 0x77dev** [comment]
Maybe use a golang and connect it to nodejs, or create tor bindings.

**Comment by 0x77dev** [comment]
The issue hasn't been updated in a long time.
