### ISSUE TITLE
unavailable service event

### ISSUE THREAD

**Issue by iamyellow** [aholstenson/ataraxia#34]
Hi! thanks for this amazing lib!
I'm building a custom transport and I'm having some issues: peer A pubishes a service RPC method and  peer B discovers it (onServiceAvailable is triggered). if A loses connection, onServiceUnavailable is not triggered on B side. The weird thing is I can see the logs of onNodeUnavailable event triggered. Is the unavailable event triggered in this situation?

**Comment by iamyellow** [comment]
I've been doing some research and I understand what is happening:
- if the service is available by the time `handleNodeAvailable` is called on B side, everything is triggered as expected
- BUT if we register the service (on A) after, the `onServiceUnavailable` is not triggered because the node.id is not in the state map:
https://github.com/aholstenson/ataraxia/blob/a0bee4f8d9a6c2349cc6bea6c4e7f9f478da44b6/packages/services/src/Services.ts#L599

**Comment by iamyellow** [comment]
ok, if we add the reflect to node services Map:
`data.services.set(id, reflect)` 
before this:
https://github.com/aholstenson/ataraxia/blob/a0bee4f8d9a6c2349cc6bea6c4e7f9f478da44b6/packages/services/src/Services.ts#L710
then works as expected. 
I'll try to PR this with a test.

**Comment by iamyellow** [comment]
done! https://github.com/aholstenson/ataraxia/pull/35

**Comment by aholstenson** [comment]
Thanks for reporting this issue, looking deeper into it, and fixing it. I've merged the PR and will do a release shortly

**Comment by aholstenson** [comment]
Did the release, your fix is now available in 0.12.1 of `ataraxia-services`, thanks again!
